# -*- coding: utf-8 -*-
"""07/10/2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-cUjKdaAEVx43qDNGVJnro-bgxHc0TL
"""

# !pip install flask_cors

# !pip install Config

# !pip install flask

# !pip install smartapi-python

# !pip install pyotp

import pyotp

api_key = 'fIHJLOgD'
clientId = 'P545635'
pwd = '2324'
token = "FNYXKJSXGRSOFURGQWKZAEX5DQ"
totp = pyotp.TOTP(token).now()

correlation_id = "abc456"

from flask import Flask, request, jsonify
from flask_cors import CORS, cross_origin
from SmartApi import SmartConnect
from SmartApi.smartWebSocketV2 import SmartWebSocketV2
import threading
import datetime as datetime
import time
import pandas as pd



app = Flask(__name__)

df = pd.DataFrame([], columns=['Thread_id','Time_slot','strik_price','Entry_price','SL_price','Current_price','Realize_Gain','Total_Gain','Num_of_reEntry','total_reEntry'])

cors = CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'


def help():
    while 1:
        time.sleep(1)
        temp = df[df['total_reEntry']!=-1]
        print(temp.to_string(index=False,header=False))
        # if(len(df) > 0):
        #     print(df.to_string(index=False,header=False),flush=True)

def login():

    global smartApi
    global Session_Obj

    smartApi = SmartConnect(api_key)
    Session_Obj = smartApi.generateSession(clientId, pwd, totp)

def GetToken(tradingSymbol):
    try:
        df = pd.read_excel("Book2.xlsx",sheet_name=0)
        df = df[(df['symbol'] == tradingSymbol)]
        # print(df)

        if not df.empty:
            token = df.iloc[0]['token']
            return int(token)
        else:
            print(f"Symbol '{tradingSymbol}' not found in the Excel file.")
            return None

    except FileNotFoundError:
        print(f"File  not found.")
        return None

    except Exception as e:
        print(f"Error occurred: {e}")
        return None

def getCurrentPrice(TradingSymbol,SymbolToken):
    return smartApi.ltpData("NFO" ,TradingSymbol,SymbolToken)['data']['ltp']

def Process_Order(data,id):

    Expiry = data['expiry'][0:5] + data['expiry'][-2:]
    Index = data['index']
    Strike = data['strikePrice']
    MaxReEntry = data['reEntry']
    OrderTime = data['orderTime']

    TradingSymbol = Index + Expiry + Strike + data['optionType']
    SymbolToken = GetToken(TradingSymbol)

    df.loc[df['Thread_id']==id,'Time_slot'] = OrderTime
    df.loc[df['Thread_id']==id,'strik_price'] = Strike
    df.loc[df['Thread_id']==id,'total_reEntry'] = MaxReEntry


    print(TradingSymbol," ",SymbolToken)

    hour = OrderTime[:2]
    minute = OrderTime[-2:]

    OrderTimeinMinutes = int(hour) * 60 + int(minute)
    CurrentTime = datetime.datetime.now().hour * 60 + datetime.datetime.now().minute


    if OrderTimeinMinutes > CurrentTime:
        seconds = (OrderTimeinMinutes - CurrentTime ) * 60
        print(" Sleeping For ",seconds)
        time.sleep(seconds)

# {'index': 'BANKNIFTY', 'expiry': '13SEP2023', 'transactionType': '', 'optionType': '', 'strikePrice': '', 'orderTime': '21:27', 'stopLoss': '', 'reEntry': '', 'priceType': 'MARKET', 'limitPrice': '', 'lotSize': 1}
    SellPrice = 0
    CurrentReEntry = 0
    Exit = False
    Realized_Gain = 0
    UnRealized_Gain = 0
    Total_Gain = 0


    if data['transactionType'] == "SELL":

        if data['priceType'] == 'MARKET':
            SellPrice = getCurrentPrice(TradingSymbol,SymbolToken) # Get Price From Live Market

        elif data['priceType'] == 'LIMIT':
            SellPrice = int(data['limitPrice'])


        StopLossPrice = SellPrice * (int(data['stopLoss']) + 100)/100
        # print(SellPrice," ",StopLossPrice)

        df.loc[df['Thread_id']==id,'Entry_price'] = SellPrice
        df.loc[df['Thread_id']==id,'SL_price'] = StopLossPrice
        while 1:

            CurrentPrice = getCurrentPrice(TradingSymbol,SymbolToken) # Get Price From Live Market
            df.loc[df['Thread_id']==id,'Current_price'] = CurrentPrice

            if( (CurrentPrice >= StopLossPrice) & (not Exit) ):
                Exit = True
                Realized_Gain = Realized_Gain + ( SellPrice - StopLossPrice ) * 25

            elif ((CurrentPrice <= SellPrice) & (Exit)):
                Exit = False
                CurrentReEntry+=1

            if (not Exit):
                UnRealized_Gain = (SellPrice - CurrentPrice) * 25
                Total_Gain = Realized_Gain + UnRealized_Gain

            # print("Current Price: ",CurrentPrice, " StopLoss Price: ",StopLossPrice," Realized Gain: ",Realized_Gain, " Total Gain: ", Total_Gain)

            df.loc[df['Thread_id']==id,'Realize_Gain'] = Realized_Gain
            df.loc[df['Thread_id']==id,'Total_Gain'] = Total_Gain
            df.loc[df['Thread_id']==id,'Num_of_reEntry'] = CurrentReEntry

            print(df.to_string(index=False,header=False),flush=True)
            # print("Total Realize Gain : " , sum(df['Realize_Gain']))

            if( (CurrentReEntry == MaxReEntry) & (Exit)):
                break

            Current_Time = datetime.datetime.now().hour * 60 + datetime.datetime.now().minute
            if Current_Time >= 960: # Stop execution after 3:30 PM
                break



    elif data['transactionType'] == "BUY":

        

        if data['priceType'] == 'MARKET':
            BuyPrice = getCurrentPrice(TradingSymbol,SymbolToken) # Get Price From Live Market

        elif data['priceType'] == 'LIMIT':
            BuyPrice = int(data['limitPrice'])


        StopLossPrice = BuyPrice * ( 100 - int(data['stopLoss']) )
        print(BuyPrice," ",StopLossPrice)

        df.loc[df['Thread_id']==id,'Entry_price'] = BuyPrice
        df.loc[df['Thread_id']==id,'SL_price'] = StopLossPrice


        while 1:

            CurrentPrice = getCurrentPrice(TradingSymbol,SymbolToken) # Get Price From Live Market
            df.loc[df['Thread_id']==id,'Current_price'] = CurrentPrice
            
            if( (CurrentPrice <= StopLossPrice) & (not Exit) ):
                Exit = True
                Realized_Gain = Realized_Gain + ( StopLossPrice - BuyPrice) * 25

            elif ((CurrentPrice >= BuyPrice) & (Exit)):
                Exit = False
                CurrentReEntry+=1

            if (not Exit):
                UnRealized_Gain = (CurrentPrice - BuyPrice) * 25
                Total_Gain = Realized_Gain + UnRealized_Gain

            # print("Current Price: ",CurrentPrice, " Realized Gain: ",Realized_Gain, " Total Gain: ", Total_Gain)

            df.loc[df['Thread_id']==id,'Realize_Gain'] = Realized_Gain
            df.loc[df['Thread_id']==id,'Total_Gain'] = Total_Gain
            df.loc[df['Thread_id']==id,'Num_of_reEntry'] = CurrentReEntry

            # print(df.to_string(index=False,header=False),flush=True)
            # print("Total Realize Gain : " , sum(df['Realize_Gain']))

            if( (CurrentReEntry == MaxReEntry) & (Exit)):
                break

            Current_Time = datetime.datetime.now().hour * 60 + datetime.datetime.now().minute
            if Current_Time >= 960: # Stop execution after 3:30 PM
                break

@app.route("/test", methods=["POST"])
def Test():
    data = request.get_json()


    df.loc[len(df)] = [0,"09:30",45600,273,300,295,100,115,2,-1]
    df.loc[len(df)-1,'Thread_id'] = len(df)
    

    threading.Thread(target=Process_Order,args=(data,len(df))).start()

    response_data = {"Status": True, "message": "Order Placed Successfully"}
    return jsonify(response_data)

if __name__ == "__main__":
    login()
    # threading.Thread(target=help).start()
    app.run(debug=True)


